.TH PHSPCONVERT 1 "July 2026" "ParticleZoo @VERSION@" "User Commands"
.SH NAME
PHSPConvert \- convert particle phase space files between formats
.SH SYNOPSIS
.B PHSPConvert
.RI [ OPTIONS ]
.I inputfile
.I outputfile
.SH DESCRIPTION
.B PHSPConvert
converts Monte Carlo particle phase space files between the formats
supported by the ParticleZoo library (EGS, IAEA, MCNP, TOPAS, penEasy and,
if compiled with ROOT support, ROOT). Input and output formats are
detected automatically from the file extensions unless overridden with
.B \-\-inputFormat
and
.BR \-\-outputFormat .
The output file must be different from the input file.
.PP
Particles can be filtered (by species, energy, position or generation)
and transformed (flipped, projected, or assigned constant values) during
conversion.
Positions are expressed in centimetres and kinetic energies in MeV.
.SH OPTIONS
.SS General
.TP
.BR \-h ", " \-\-help
Display a help message listing all options.
.TP
.BR \-v ", " \-\-version
Display version information.
.TP
.BR \-f ", " \-\-formats
List all supported file formats.
.TP
.BI \-\-inputFormat " FORMAT"
Force the input file format (default: auto-detect from the file extension).
.TP
.BI \-\-outputFormat " FORMAT"
Force the output file format (default: auto-detect from the file extension).
.TP
.BI \-\-maxParticles " N"
Maximum number of particles to process (default: unlimited).
.TP
.BI \-\-preserveConstants " true/false"
Preserve constant values from the input file if present (default: true).
.TP
.B \-\-errorOnWarning
Treat warnings as errors when determining the exit code.
.SS Particle filtering
.TP
.B \-\-photonsOnly
Only convert photons, rejecting all other particles.
.TP
.B \-\-electronsOnly
Only convert electrons, rejecting all other particles.
.TP
.BI \-\-filterByPDG " CODE"
Only convert particles with the specified PDG particle code.
.TP
.B \-\-primariesOnly
Only process primary particles.
.TP
.B \-\-excludePrimaries
Exclude primary particles from processing.
.TP
.BI \-\-generations " MIN MAX"
Filter particles by generation range.
.TP
.BI \-\-minEnergy " E"
Only convert particles with kinetic energy >= E (MeV).
.TP
.BI \-\-maxEnergy " E"
Only convert particles with kinetic energy <= E (MeV).
.TP
.BI \-\-minRadius " R"
Minimum radial distance in the XY plane (cm) for particles to be converted.
.TP
.BI \-\-maxRadius " R"
Maximum radial distance in the XY plane (cm) for particles to be converted.
.TP
\fB\-\-minX\fP \fIV\fP, \fB\-\-maxX\fP \fIV\fP, \fB\-\-minY\fP \fIV\fP, \fB\-\-maxY\fP \fIV\fP, \fB\-\-minZ\fP \fIV\fP, \fB\-\-maxZ\fP \fIV\fP
Position limits in cm for particles to be converted.
.SS Particle transforms
.TP
.BR \-\-flipX ", " \-\-flipY ", " \-\-flipZ
Flip the corresponding direction component of all particles.
.TP
\fB\-\-projectToX\fP \fIV\fP, \fB\-\-projectToY\fP \fIV\fP, \fB\-\-projectToZ\fP \fIV\fP
Project particles along their direction of travel to the given position (cm).
.TP
\fB\-X\fP \fIV\fP, \fB\-\-constantX\fP \fIV\fP
Write all particles with this constant X position. The analogous options
.BR \-Y ", " \-Z ", " \-Px ", " \-Py ", " \-Pz " and " \-W
set constant Y/Z positions, X/Y/Z directional cosines and weight.
.SS EGS format options
.TP
.B \-\-EGS\-ignore\-header\-count
Ignore the particle count in the header and calculate it from the file size.
.TP
.BI \-\-EGS\-latch\-option " 1|2|3"
LATCH interpretation option when reading/writing EGS files.
.TP
.BI \-\-EGS\-mode " MODE0|MODE2"
EGS phase space file mode (default: MODE0).
.TP
.BI \-\-EGS\-particleZ " V"
Z position to assume for all particles in the EGS file (default: 0).
.SS IAEA format options
.TP
.BI \-\-IAEA\-file\-type " PHSP_FILE|PHSP_GENERATOR"
File type recorded in the IAEA header (default: PHSP_FILE).
.TP
.BI \-\-IAEA\-header\-template " FILE"
Copy phase space attributes from an existing IAEA header file.
.TP
.B \-\-IAEA\-ignore\-checksum
Ignore checksum errors when reading an IAEA file.
.TP
.BR \-\-IAEA\-ilb1 " .. " \-\-IAEA\-ilb5
Include the corresponding PENELOPE ILB extra long in the IAEA file.
.TP
.B \-\-IAEA\-incrementals
Include the incremental history number extra long.
.TP
.BI \-\-IAEA\-index " TEXT"
Index string for the IAEA header.
.TP
.B \-\-IAEA\-latch
Include the EGS LATCH extra long.
.TP
.BI \-\-IAEA\-title " TEXT"
Title string for the IAEA header.
.TP
.BR \-\-IAEA\-xlast ", " \-\-IAEA\-ylast ", " \-\-IAEA\-zlast
Include the corresponding XLAST/YLAST/ZLAST extra float.
.SS TOPAS format options
.TP
.BI \-\-TOPAS\-format " ASCII|BINARY|LIMITED"
TOPAS phase space format to write (default: BINARY).
.TP
.B \-\-TOPAS\-single\-pseudo
Write a single pseudo-particle at the end of a TOPAS binary file to account
for all empty histories, instead of interleaving them throughout the file.
.SH EXIT STATUS
Returns 0 on success and non-zero on error. With
.BR \-\-errorOnWarning ,
warnings also produce a non-zero exit status.
.SH EXAMPLES
.nf
PHSPConvert input.egsphsp output.IAEAphsp
PHSPConvert \-\-maxParticles 500000 simulation.phsp converted.egsphsp
PHSPConvert \-\-inputFormat TOPAS \-\-outputFormat IAEA input.phsp output.IAEAphsp
PHSPConvert \-\-photonsOnly \-\-minEnergy 0.5 beam.egsphsp photons.IAEAphsp
.fi
.SH SEE ALSO
.BR PHSPCombine (1),
.BR PHSPImage (1),
.BR PHSPSplit (1)
.PP
Project homepage:
.I https://github.com/dobrienphd/ParticleZoo
.SH AUTHOR
Daniel O'Brien. ParticleZoo is released under the MIT license.
